# # Use Node.js base image
# FROM node:22-alpine

# WORKDIR /app

# # Copy package files and install dependencies
# COPY package*.json ./
# RUN npm install

# # Copy all files
# COPY . .

# # Expose Vite dev port
# EXPOSE 5173

# # Run Vite in development mode
# CMD ["npm", "run", "dev"]




# frontend/client/Dockerfile

FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
